package com.saita.nightsoulsmod.common.items;

import java.util.List;

import net.minecraft.client.util.ITooltipFlag;
import net.minecraft.entity.LivingEntity;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.potion.EffectInstance;
import net.minecraft.potion.Effects;
import net.minecraft.util.text.ITextComponent;
import net.minecraft.util.text.StringTextComponent;
import net.minecraft.world.World;

public class StarBit extends Item {

	public StarBit(Properties properties) {
		super(properties);

	}
	
	@Override
    public void addInformation(ItemStack stack, World worldIn, List<ITextComponent> tooltip, ITooltipFlag flagIn)
    {
    	
    tooltip.add(new StringTextComponent("§7Automatically generated by the §1Milky Way Armor§7. Eat them for powerful buffs !"));
	super.addInformation(stack, worldIn, tooltip, flagIn);
    }
	
	@Override
	public ItemStack onItemUseFinish(ItemStack stack, World worldIn, LivingEntity entityLiving) {
		
		entityLiving.addPotionEffect(new EffectInstance(Effects.REGENERATION, 400, 2));
		entityLiving.addPotionEffect(new EffectInstance(Effects.SPEED, 400, 3));
		entityLiving.addPotionEffect(new EffectInstance(Effects.ABSORPTION, 400, 1));
		entityLiving.addPotionEffect(new EffectInstance(Effects.STRENGTH, 400, 3));
		entityLiving.addPotionEffect(new EffectInstance(Effects.HASTE, 400, 2));
		

		return super.onItemUseFinish(stack, worldIn, entityLiving);
	}

}
